name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
        env:
          TS_CLIENT_ID: ${{ secrets.TS_CLIENT_ID }}
          TS_CLIENT_SECRET: ${{ secrets.TS_CLIENT_SECRET }}